### ISSUE TITLE
setRoot() method not deactivate binded viewmodels

### ISSUE THREAD

**Issue by oguzhaneren** [BlueSpire/Durandal#665] opened 2015-07-13 14:02 UTC
Hi,

I have two shell for login scenarios. shellguest.js and shell.js

I change shell using app.setRoot("shell") after login. When  user click the logout I change shell to shellguest, app.setRoot("shellguest"). However, app.SetRoot doesn't trigger deactivate method of current viewmodels so all bindings not cleared after change shell. (it may be occur highly memory consumption and unwanted bindings)

**Comment by gpltaylor** [comment] 2015-07-14 15:57
I am not 100% positive but I think the Shell uses compose to render. This does not us the Activator.js so life cycle events are not hooked up. This is also the case if you use knockout compose to embed a widget into an existing view. That also does not hook up into the life cycle. 
I can't speak for Rob but this appears to be by design.

I think however you do get deactive so you can place and cleanup code here.

To be honest with you I never thought about using setRoot dynamically. I have always looked at this as being bootstrap code. I can't think of why you would want to do this? Dynamic menus and designs can be composed based on the login status. Let me know..

**Comment by EisenbergEffect** [comment] 2018-11-30 08:41
Closing since Durandal has been superseded by Aurelia just shy of four years ago.

**Closed by EisenbergEffect** 2018-11-30 08:41 UTC
