### ISSUE TITLE
Module reuse with activation data fails.

### ISSUE THREAD

**Issue by giuseppelt** [BlueSpire/Durandal#609] opened 2014-12-03 16:43 UTC
It fails because the `router.activeItem.settings.areSameItem` returns false due to different activation data:

``` javascript
        function (currentItem, newItem, currentActivationData, newActivationData) {
            if (currentItem == newItem) {
                return compareArrays(currentActivationData, newActivationData);
            }
            return false;
        };
```

The root cause is in this router code:

``` javascript
if (canReuseCurrentActivation(instruction)) {
    var tempActivator = activator.create();
    tempActivator.forceActiveItem(currentActivation); //enforce lifecycle without re-compose
    tempActivator.settings.areSameItem = activeItem.settings.areSameItem;
    tempActivator.settings.findChildActivator = activeItem.settings.findChildActivator;
    ensureActivation(tempActivator, currentActivation, instruction);
}
```

where the `tempActivator` is created without the old activation data, so when it comes to test by `areSameItem`, it always fails.

A fast solution could be:
- modify with `forceActiveItem(currentActivation, currentActivationData)`
- because `currentActivatonData` is not exposed by the activator, expose it or wrap it with a get function.

**Comment by davismj** [comment] 2015-02-26 01:28
Can you provide a bit more details on the steps to reproduce your issue. The way I understand it, this works just fine.

**Comment by EisenbergEffect** [comment] 2018-11-30 08:43
Closing since Durandal has been superseded by Aurelia just shy of four years ago.

**Closed by EisenbergEffect** 2018-11-30 08:43 UTC
