### ISSUE TITLE
Router: IE8 fails parsing query strings

### ISSUE THREAD

**Issue by johnhunter** [BlueSpire/Durandal#615] opened 2015-01-06 18:27 UTC
When using the router with a query string IE8 fails to return the query key/values

**For example:**
define a route `'product/:id'`
navigate to `product/123?color=red`

**Expected:**
`activate` called with args `123, { color: 'red' }`

**Actual (IE8):**
`activate` called with args `123, {}`

**Version:**
2.1.0

This appears to be an issue with [x-bowser compatibility](http://blog.stevenlevithan.com/archives/cross-browser-split) when using string.split with regexs. The following line fails to return a value for the param:
[src/plugins/js/router.js#L550](https://github.com/BlueSpire/Durandal/blob/master/src/plugins/js/router.js#L550)

Changing to use string.match solves the problem. I'll raise a pull request.

```js
var parts = pair.match(/(.+)?=(.+)?/),
    key = parts[1],
    value = parts[2] && decodeURIComponent(parts[2].replace(/\+/g, ' '));
```

**Comment by PWKad** [comment] 2015-02-19 04:32
@johnhunter Seems to be an issue worth solving, will need to take the time to repro the issue unless you have a repo that reproduces?

**Comment by johnhunter** [comment] 2015-02-21 14:10
Have added a repro case in a fork of the dFiddle repo. Relevant url is http://johnhunter.github.io/dFiddle-2.0/#router - follow the links on this page to see params displayed on screen.

Have confirmed IE8 returns an empty object on activation.

**Comment by PWKad** [comment] 2015-02-21 15:36
Awesome will take a look here in a bit thanks!

**Comment by PWKad** [comment] 2015-02-25 12:29
@johnhunter It looks like dFiddle is using Durandal.js 2.1 in that example but is missing the latest changes to accommodate this issue from this commit - https://github.com/BlueSpire/Durandal/commit/fe4ce68986e427ca7e0462e83c5e4b6f845ceb6b

There is a separate open issue #628 currently open related to this so I think we can close this out for now @EisenbergEffect

**Comment by EisenbergEffect** [comment] 2015-02-25 14:10
Closing.

**Closed by EisenbergEffect** 2015-02-25 14:10 UTC
